apiVersion: weka.weka.io/v1alpha1
kind: WekaCluster
metadata:
  name: weka-axon
  namespace: weka-operator-system
spec:
  template: dynamic
  dynamicTemplate:
    computeContainers: 6
    computeCores: 3
    computeHugepages: 9216
    driveContainers: 6
    driveCores: 2
    numDrives: 4
  driversDistService: https://drivers.weka.io
  gracefulDestroyDuration: "0"
  image: quay.io/weka.io/weka-in-container:4.4.21.2
  imagePullSecret: "weka-quay-io-secret"
  network:
    udpMode: false
  nodeSelector:
    weka.io/supports-backends: "true"
  ports:
    basePort: 15000
  rawTolerations:
    - key: "weka.io/axon"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"
